version: "3.9"

services:
  frontend:
    build: /frontend
    ports:
      - "3000:3000"
    networks:
      - overlay

  api:
    image: /api
    networks:
       - overlay
    ports:
      - "8000:8000"

networks:
  overlay: